export enum Gamestate{
  LOBBY,
  PREPARATION,
  DICE,
  TURN,
  AWAIT_TRADE,
  INITIAL_PLACE_FORWARD,
  INITIAL_PLACE_BACKWARD,
  HALF_RESOURCES,
  PLACE_ROBBER,
  CHOOSE_ROBBED,
  AWAIT_GOLD_SELECTION,
}
